import argparse
import json
import os
import shutil
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

from telemetry_paths import find_newest_session, get_sessions_dir, safe_read_json


SCHEMA_VERSION_EXPORT = "interaction_geometry.target_handoff_export.v1"
SCHEMA_VERSION_CANDIDATE = "interaction_geometry.target_handoff_candidate.v1"
SCHEMA_VERSION_INDEX = "interaction_geometry.target_handoff_index.v1"
SAFETY_WARNING = "no mouse, keyboard, click, or menu action is generated by this project"


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def json_dump_compact(data) -> str:
    return json.dumps(data, separators=(",", ":"), sort_keys=False)


def resolve_session(args) -> Path | None:
    if args.session:
        return Path(args.session).expanduser()

    return find_newest_session(get_sessions_dir(args.sessions_dir))


def paths_for(session: Path) -> dict[str, Path]:
    geometry_dir = session / "interaction_geometry"
    handoff_dir = geometry_dir / "handoff"
    return {
        "geometryDir": geometry_dir,
        "candidates": geometry_dir / "target_candidates.jsonl",
        "candidatesIndex": geometry_dir / "target_candidates_index.json",
        "handoffDir": handoff_dir,
        "latestJson": handoff_dir / "latest_candidates.json",
        "latestJsonl": handoff_dir / "latest_candidates.jsonl",
        "index": handoff_dir / "handoff_index.json",
    }


def read_jsonl(path: Path) -> tuple[list[dict], list[str]]:
    records = []
    warnings = []

    if not path.exists():
        warnings.append(f"missing input: {path}")
        return records, warnings

    try:
        with path.open("r", encoding="utf-8") as file:
            for line_number, line in enumerate(file, start=1):
                text = line.strip()

                if not text:
                    continue

                try:
                    record = json.loads(text)
                except json.JSONDecodeError as error:
                    warnings.append(f"{path.name}:{line_number}: invalid JSON: {error.msg}")
                    continue

                if isinstance(record, dict):
                    records.append(record)
                else:
                    warnings.append(f"{path.name}:{line_number}: expected JSON object")
    except OSError as error:
        warnings.append(f"could not read {path}: {error}")

    return records, warnings


def target_for(candidate: dict) -> dict:
    value = candidate.get("target")
    return value if isinstance(value, dict) else {}


def frame_for(candidate: dict) -> dict:
    value = candidate.get("frame")
    return value if isinstance(value, dict) else {}


def geometry_for(candidate: dict) -> dict:
    value = candidate.get("geometry")
    return value if isinstance(value, dict) else {}


def scoring_for(candidate: dict) -> dict:
    value = candidate.get("scoring")
    return value if isinstance(value, dict) else {}


def target_name(candidate: dict) -> str:
    target = target_for(candidate)

    for key in ("name", "targetName", "objectName", "itemName", "npcName", "fallbackName", "targetId"):
        value = target.get(key)

        if value is not None and str(value).strip():
            return str(value).strip()

    target_type = target.get("targetType") or "Target"
    target_id = target.get("rawId")

    if target_id is None:
        target_id = target.get("id")

    return f"{target_type}[{target_id}]" if target_id is not None else str(target_type)


def target_ids(candidate: dict) -> list[str]:
    target = target_for(candidate)
    values = []

    for key in ("id", "rawId", "targetId"):
        value = target.get(key)

        if value is not None:
            values.append(str(value))

    return values


def selected_tick_ids(candidates: list[dict], args) -> set[int] | None:
    if args.tick is not None:
        return {args.tick}

    if args.latest is not None:
        ticks = sorted({candidate.get("tickId") for candidate in candidates if isinstance(candidate.get("tickId"), int)})
        return set(ticks[-args.latest :])

    return None


def candidate_matches(candidate: dict, args, selected_ticks: set[int] | None) -> bool:
    target = target_for(candidate)

    if selected_ticks is not None and candidate.get("tickId") not in selected_ticks:
        return False

    if args.target_type and args.target_type != "all" and str(target.get("targetType") or "") != args.target_type:
        return False

    if args.role and str(target.get("targetRole") or "").lower() != args.role.lower():
        return False

    if args.category and str(target.get("targetCategory") or "").lower() != args.category.lower():
        return False

    if args.name:
        haystack = " ".join(
            str(value or "")
            for value in (
                target_name(candidate),
                target.get("name"),
                target.get("targetName"),
                target.get("targetType"),
                target.get("targetRole"),
                target.get("targetCategory"),
                " ".join(target.get("targetTags") or []),
                target.get("id"),
                target.get("rawId"),
                target.get("targetId"),
            )
        ).lower()

        if args.name.lower() not in haystack:
            return False

    if args.min_score is not None:
        score = candidate.get("score")

        if not isinstance(score, (int, float)) or score < args.min_score:
            return False

    return True


def filter_summary(args) -> dict:
    return {
        "tick": args.tick,
        "latest": args.latest,
        "category": args.category,
        "role": args.role,
        "targetType": args.target_type,
        "name": args.name,
        "limit": args.limit,
        "minScore": args.min_score,
    }


def handoff_candidate(candidate: dict) -> dict:
    target = target_for(candidate)
    frame = frame_for(candidate)
    geom = geometry_for(candidate)
    scoring = scoring_for(candidate)
    return {
        "schemaVersion": SCHEMA_VERSION_CANDIDATE,
        "sessionId": candidate.get("sessionId"),
        "tickId": candidate.get("tickId"),
        "timestampUtc": candidate.get("timestampUtc"),
        "rank": candidate.get("rank"),
        "score": candidate.get("score"),
        "target": {
            "targetId": target.get("targetId"),
            "targetType": target.get("targetType"),
            "name": target_name(candidate),
            "id": target.get("id"),
            "rawId": target.get("rawId"),
            "targetRole": target.get("targetRole"),
            "targetCategory": target.get("targetCategory"),
            "targetTags": target.get("targetTags") if isinstance(target.get("targetTags"), list) else [],
        },
        "frame": {
            "path": frame.get("path"),
            "exists": frame.get("exists"),
            "width": frame.get("width"),
            "height": frame.get("height"),
        },
        "geometry": {
            "coordinateSpace": geom.get("coordinateSpace"),
            "aimPoint": geom.get("aimPoint"),
            "preferredAimGeometryType": geom.get("preferredAimGeometryType"),
            "preferredAimGeometry": geom.get("preferredAimGeometry"),
            "aimBounds": geom.get("aimBounds"),
            "availableGeometryTypes": geom.get("availableGeometryTypes") if isinstance(geom.get("availableGeometryTypes"), list) else [],
            "geometryQuality": geom.get("geometryQuality"),
        },
        "scoring": {
            "scoreParts": scoring.get("scoreParts") if isinstance(scoring.get("scoreParts"), list) else [],
            "reasons": scoring.get("reasons") if isinstance(scoring.get("reasons"), list) else [],
            "penalties": scoring.get("penalties") if isinstance(scoring.get("penalties"), list) else [],
        },
        "handoff": {
            "readOnly": True,
            "actionGenerated": False,
            "inputGenerated": False,
            "intendedUse": "geometry inspection / external analysis",
            "warning": SAFETY_WARNING,
        },
    }


def top_candidate_summary(candidates: list[dict], limit: int = 10) -> list[dict]:
    summary = []

    for candidate in candidates[:limit]:
        target = candidate.get("target") if isinstance(candidate.get("target"), dict) else {}
        geom = candidate.get("geometry") if isinstance(candidate.get("geometry"), dict) else {}
        summary.append(
            {
                "rank": candidate.get("rank"),
                "score": candidate.get("score"),
                "tickId": candidate.get("tickId"),
                "targetType": target.get("targetType"),
                "name": target.get("name"),
                "id": target.get("id"),
                "rawId": target.get("rawId"),
                "targetCategory": target.get("targetCategory"),
                "preferredAimGeometryType": geom.get("preferredAimGeometryType"),
                "aimPoint": geom.get("aimPoint"),
            }
        )

    return summary


def index_for(session: Path, paths: dict[str, Path], source_count: int, selected: list[dict], warnings: list[str]) -> dict:
    type_counts = Counter()
    role_counts = Counter()
    category_counts = Counter()
    geometry_counts = Counter()

    for candidate in selected:
        target = candidate.get("target") if isinstance(candidate.get("target"), dict) else {}
        geom = candidate.get("geometry") if isinstance(candidate.get("geometry"), dict) else {}
        type_counts[target.get("targetType") or "unknown"] += 1
        role_counts[target.get("targetRole") or "unknown"] += 1
        category_counts[target.get("targetCategory") or "unknown"] += 1
        geometry_counts[geom.get("preferredAimGeometryType") or "none"] += 1

    return {
        "schemaVersion": SCHEMA_VERSION_INDEX,
        "generatedAtUtc": utc_now(),
        "sessionPath": str(session),
        "sourceTargetCandidatesPath": str(paths["candidates"]),
        "sourceCandidateCount": source_count,
        "selectedCandidateCount": len(selected),
        "countsByTargetType": dict(type_counts.most_common()),
        "countsByRole": dict(role_counts.most_common()),
        "countsByCategory": dict(category_counts.most_common()),
        "countsByPreferredAimGeometryType": dict(geometry_counts.most_common()),
        "topCandidateSummary": top_candidate_summary(selected),
        "outputPaths": {
            "latestCandidatesJson": str(paths["latestJson"]),
            "latestCandidatesJsonl": str(paths["latestJsonl"]),
            "handoffIndexJson": str(paths["index"]),
        },
        "warnings": warnings[:100],
    }


def atomic_write_outputs(paths: dict[str, Path], payload: dict, selected: list[dict], index: dict) -> None:
    handoff_dir = paths["handoffDir"]
    temp_dir = handoff_dir.parent / f".tmp-target-handoff-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S%f')}-{os.getpid()}"

    if temp_dir.exists():
        shutil.rmtree(temp_dir)

    temp_dir.mkdir(parents=True)

    try:
        with (temp_dir / "latest_candidates.json").open("w", encoding="utf-8") as file:
            json.dump(payload, file, indent=2)
            file.write("\n")

        with (temp_dir / "latest_candidates.jsonl").open("w", encoding="utf-8") as file:
            for candidate in selected:
                file.write(json_dump_compact(candidate))
                file.write("\n")

        with (temp_dir / "handoff_index.json").open("w", encoding="utf-8") as file:
            json.dump(index, file, indent=2)
            file.write("\n")

        handoff_dir.mkdir(parents=True, exist_ok=True)
        os.replace(temp_dir / "latest_candidates.json", paths["latestJson"])
        os.replace(temp_dir / "latest_candidates.jsonl", paths["latestJsonl"])
        os.replace(temp_dir / "handoff_index.json", paths["index"])
    finally:
        if temp_dir.exists():
            shutil.rmtree(temp_dir)


def export_target_handoff(session: Path, args) -> tuple[dict, dict]:
    session = session.expanduser().resolve()
    paths = paths_for(session)
    source_candidates, warnings = read_jsonl(paths["candidates"])

    if not paths["candidates"].exists():
        raise RuntimeError("target_candidates.jsonl is missing. Run python telemetry-viewer\\select_target_candidates.py first.")

    _source_index = safe_read_json(paths["candidatesIndex"])
    selected_ticks = selected_tick_ids(source_candidates, args)
    selected_source = [
        candidate
        for candidate in source_candidates
        if candidate_matches(candidate, args, selected_ticks)
    ][: args.limit]
    selected = [handoff_candidate(candidate) for candidate in selected_source]
    payload = {
        "schemaVersion": SCHEMA_VERSION_EXPORT,
        "generatedAtUtc": utc_now(),
        "sessionPath": str(session),
        "filterSummary": filter_summary(args),
        "candidateCount": len(selected),
        "candidates": selected,
    }
    index = index_for(session, paths, len(source_candidates), selected, warnings)
    atomic_write_outputs(paths, payload, selected, index)
    return payload, index


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Export a stable read-only handoff payload from existing ranked target candidates. "
            "This does not generate input, clicks, menu actions, or automation."
        )
    )
    parser.add_argument("--session", help="Telemetry session directory to inspect.")
    parser.add_argument("--sessions-dir", help="Override telemetry sessions directory when --session is omitted.")
    parser.add_argument("--tick", type=int, help="Only export candidates for one tick.")
    parser.add_argument("--latest", type=int, metavar="N", help="Only export candidates from the latest N candidate ticks.")
    parser.add_argument("--category", help="Case-insensitive exact target category filter.")
    parser.add_argument("--role", help="Case-insensitive exact target role filter.")
    parser.add_argument("--target-type", default="all", help="Target type filter, or all. Default: all.")
    parser.add_argument("--name", help="Case-insensitive text filter against target name/type/role/category/tags/id fields.")
    parser.add_argument("--limit", type=int, default=20, help="Maximum candidates to export. Default: 20.")
    parser.add_argument("--min-score", type=float, help="Minimum candidate score.")
    parser.add_argument("--json", action="store_true", help="Print selected handoff candidates as JSON lines.")
    args = parser.parse_args()

    if args.latest is not None and args.latest < 1:
        parser.error("--latest must be positive")

    if args.limit < 1:
        parser.error("--limit must be positive")

    return args


def print_human(payload: dict, index: dict) -> None:
    print(f"session: {payload['sessionPath']}")
    print(f"candidate count: {payload['candidateCount']}")
    print(f"output latest_candidates.json: {index['outputPaths']['latestCandidatesJson']}")
    print(f"output latest_candidates.jsonl: {index['outputPaths']['latestCandidatesJsonl']}")
    print(f"output handoff_index.json: {index['outputPaths']['handoffIndexJson']}")
    print("top candidates:")

    for candidate in payload["candidates"][:10]:
        target = candidate.get("target", {})
        geom = candidate.get("geometry", {})
        aim = geom.get("aimPoint") if isinstance(geom.get("aimPoint"), dict) else {}
        aim_text = (
            f"{aim.get('x'):.0f},{aim.get('y'):.0f}"
            if isinstance(aim.get("x"), (int, float)) and isinstance(aim.get("y"), (int, float))
            else "-"
        )
        print(
            f"  rank={candidate.get('rank')} score={candidate.get('score')} tick={candidate.get('tickId')} "
            f"type={target.get('targetType')} name=\"{target.get('name')}\" "
            f"category={target.get('targetCategory')} geometry={geom.get('preferredAimGeometryType')} aim={aim_text}"
        )

    if index["warnings"]:
        print("warnings:")

        for warning in index["warnings"][:20]:
            print(f"  - {warning}")


def main() -> int:
    args = parse_args()
    session = resolve_session(args)

    if session is None:
        print(f"No sessions found in: {get_sessions_dir(args.sessions_dir)}")
        return 1

    try:
        payload, index = export_target_handoff(session, args)
    except RuntimeError as error:
        print(f"session: {session}")
        print(str(error))
        return 1

    if args.json:
        for candidate in payload["candidates"]:
            print(json_dump_compact(candidate))
    else:
        print_human(payload, index)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
